import pandas as pd
from database.mongo_setup import get_db

def setup_contractor_module():
    # 1. Get the database connection from your separate file
    db = get_db()
    
    if db is not None:
        print("Connected to BMC_Waste_DB")
        contractor_col = db["contractors"]

        # 2. Import the Faker data from your CSV
        try:
            df = pd.read_csv('data_source/1_Contractor_Details.csv')
            data = df.to_dict(orient='records')
            
            # 3. Clean and Insert
            contractor_col.delete_many({}) 
            contractor_col.insert_many(data)
            print(f"✅ Successfully loaded {len(data)} Contractors into MongoDB.")
            
        except Exception as e:
            print(f"❌ Error loading CSV: {e}")
    else:
        print("❌ Database connection failed. Is MongoDB running?")

# This part tells Python to run the function when you start the file
if __name__ == "__main__":
    setup_contractor_module()
def find_contractor(c_id):
    db = get_db()
    if db:
        # We look for the ID generated by your Faker script
        contractor = db["contractors"].find_one({"contractor_id": c_id})
        
        if contractor:
            print(f"🔍 Found: {contractor['name']} from {contractor['company']}")
            return contractor
        else:
            print("⚠️ Contractor not found.")
            return None
