import requests
import time

def test_penalties_flow():
    print("--- Testing Penalty Alerts Flow via HTTP ---")
    base_url = "http://localhost:8002"
    
    # 1. Fetch BMC Penalties Grouped by Site
    print("\n[BMC] Fetching Penalties Grouped by Site...")
    res = requests.get(f"{base_url}/bmc/penalties/by-site")
    print("Status:", res.status_code)
    try:
        data = res.json()
        print(f"Total Sites with Active Penalties: {len(data)}")
        if len(data) > 0:
            print("Sample site penalty data:", data[0])
    except Exception as e:
        print("Error reading JSON:", str(e))
        
    # 2. Fetch BMC Alerts generated by the background task
    # Background task fires immediately on startup
    print("\n[BMC] Fetching BMC Alerts...")
    time.sleep(2) # Give background task a bit of time to seed data
    res = requests.get(f"{base_url}/alerts/bmc")
    print("Status:", res.status_code)
    try:
        data = res.json()
        print(f"Total BMC Alerts: {len(data)}")
        if len(data) > 0:
            print("Sample BMC Alert:", data[0])
    except Exception as e:
        print("Error reading JSON:", str(e))

    # 3. Fetch Contractor Alerts (needs login to get token)
    # First, let's pick a random contractor_id from the first penalty group or sign up
    # It's easier if we just sign up a contractor, wait, wait
    # The contractor needs to match an existing contractor_id for real alerts OR we can rely on our script
    # to login our test contractor that does not have penalties natively, or we login as the first contractor ID.
    # Since auth uses `username`, we need a username. We don't have usernames for the seed contractors natively 
    # except those we seeded in `seed_data.py`. Let's just run the endpoint without authorization if we want to bypass?
    # Wait, the endpoint uses Depends(get_current_user) which requires token.
    # Let me just login as "testcontractor"
    print("\n[Contractor] Logging in test contractor...")
    login_res = requests.post(f"{base_url}/auth/login", json={
        "username": "testcontractor",
        "password": "securepassword123"
    })
    token = login_res.json().get("access_token")
    if token:
        print("Fetch Contractor Alerts...")
        res = requests.get(f"{base_url}/alerts/contractor", headers={"Authorization": f"Bearer {token}"})
        print("Status:", res.status_code)
        try:
            data = res.json()
            print(f"Total Contractor Alerts: {len(data)}")
        except Exception:
            pass
    else:
        print("Could not login as testcontractor to test contractor alerts.")

if __name__ == "__main__":
    test_penalties_flow()
